name: Docker Compose Workflow

on:
  schedule:
    - cron: '*/5 * * * *'  # Beachten Sie, dass GitHub eine Mindestfrequenz von 5 Minuten für cron Jobs hat
  workflow_dispatch:

jobs:
  docker-compose-up:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Start Docker Compose
      run: docker-compose up -d
    
    - name: Commit index.html changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add index.html
        git commit -m "Automatically update index.html" || echo "No changes to commit"
        git push
